export const {
  PORT = 3000,
  SALT_ROUNDS = 10,
  DB_HOST = 'localhost',
  DB_USER = 'postgres',
  DB_PORT = 5432,
  DB_PASSWORD = '1234',
  DB_DATABASE = 'backend-zoco',
  JWT_SECRET = 'backend-zoco-jwt-secret',
} = process.env;
